### ISSUE TITLE
pyasn_util_convert.py: assert error  in conversion of some 2009 RIB files

### ISSUE THREAD

**Issue by hadiasghari** [hadiasghari/pyasn#13]
20090519.0600... 
  Error parsing prefix '84.205.80.0/24'

20090609.0600... 
  Error parsing prefix '84.205.64.0/24'

Traceback (most recent call last):
  File "/home/hadi/pyasn.git/pyasn-utils/pyasn_util_convert.py", line 86, in <module>
    dat = mrtx.parse_mrt_file(f)
  File "/usr/lib64/python2.6/site-packages/pyasn-1.5.0b6-py2.6-linux-x86_64.egg/pyasn/mrtx.py", line 83, in parse_mrt_file
    origin = mrt.as_path.origin_as
  File "/usr/lib64/python2.6/site-packages/pyasn-1.5.0b6-py2.6-linux-x86_64.egg/pyasn/mrtx.py", line 240, in as_path
    path = a.path_detail()
  File "/usr/lib64/python2.6/site-packages/pyasn-1.5.0b6-py2.6-linux-x86_64.egg/pyasn/mrtx.py", line 376, in path_detail
    self._detail = self.BgpAttrASPath(self.data, self._is32)
  File "/usr/lib64/python2.6/site-packages/pyasn-1.5.0b6-py2.6-linux-x86_64.egg/pyasn/mrtx.py", line 386, in __init__
    seg = self.BgpPathSegment(buf, is32)
  File "/usr/lib64/python2.6/site-packages/pyasn-1.5.0b6-py2.6-linux-x86_64.egg/pyasn/mrtx.py", line 457, in __init__
    assert self.seg_type in (self.AS_SET, self.AS_SEQUENCE)
AssertionError

**Comment by hadiasghari** [comment]
Fixed in latest commit
